include ../defs.mk

038: o038_filter_list.ml
	$(OBC) o038_filter_list.ml -o 038_filter_list.native

039: o039_sum_tree_nodes.ml
	$(OBC) o039_sum_tree_nodes.ml -o 039_sum_tree_nodes.native

040: o040_red_black_tree.ml
	$(OBC) o040_red_black_tree.ml -o 040_red_black_tree.native

041: o041_intro_to_laziness.ml
	$(OBC) o041_intro_to_laziness.ml -o 041_intro_to_laziness.native

042: o042_intro_to_streams.ml
	$(OBC) o042_intro_to_streams.ml -o 042_intro_to_streams.native

