include ../defs.mk

001: o001_grep_lines.ml
	$(OBC) -package re.posix o001_grep_lines.ml -o 001_grep_lines.native

002: o002_hello_user.ml
	$(OBC) o002_hello_user.ml -o 002_hello_user.native

003: o003_random_int.ml
	$(OBC) o003_random_int.ml -o 003_random_int.native

004: o004_ask_time.ml
	$(OBC) -package unix o004_ask_time.ml -o 004_ask_time.native

005: o005_count_letters.ml
	$(OBC) o005_count_letters.ml -o 005_count_letters.native

006: o006_ref_name.ml
	$(OBC) o006_ref_name.ml -o 006_ref_name.native

007: o007_array_matrix.ml
	$(OBC) o007_array_matrix.ml -o 007_array_matrix.native

008: o008_mat_check_zeros.ml
	$(OBC) o008_mat_check_zeros.ml -o 008_mat_check_zeros.native

009: o009_record_matches.ml
	$(OBC) o009_record_matches.ml -o 009_record_matches.native

010: o010_basic_loops.ml
	$(OBC) o010_basic_loops.ml -o 010_basic_loops.native

011: o011_loop_interval.ml
	$(OBC) o011_loop_interval.ml -o 011_loop_interval.native

012: o012_store_function.ml
	$(OBC) o012_store_function.ml -o 012_store_function.native

013: o013_make_generator.ml
	$(OBC) o013_make_generator.ml -o 013_make_generator.native

014: o014_match_try_recursion.ml
	$(OBC) o014_match_try_recursion.ml -o 014_match_try_recursion.native

015: o015_beginner_ex1.ml
	$(OBC) o015_beginner_ex1.ml -o 015_beginner_ex1.native

016: o016_beginner_ex2.ml
	$(OBC) o016_beginner_ex2.ml -o 016_beginner_ex2.native

017: o017_beginner_ex3.ml
	$(OBC) o017_beginner_ex3.ml -o 017_beginner_ex3.native

018: o018_beginner_ex4.ml
	$(OBC) o018_beginner_ex4.ml -o 018_beginner_ex4.native

019: o019_beginner_ex5.ml
	$(OBC) o019_beginner_ex5.ml -o 019_beginner_ex5.native

020: o020_beginner_ex6.ml
	$(OBC) o020_beginner_ex6.ml -o 020_beginner_ex6.native

021: o021_beginner_ex7.ml
	$(OBC) o021_beginner_ex7.ml -o 021_beginner_ex7.native

