include ../defs.mk

022: o022_tuples_sample.ml
	$(OBC) o022_tuples_sample.ml -o 022_tuples_sample

023: o023_records_sample.ml
	$(OBC) o023_records_sample.ml -o 023_records_sample

024: o024_mutable_records_sample.ml
	$(OBC) o024_mutable_records_sample.ml -o 024_mutable_records_sample

025: o025_sum_types_basic.ml
	$(OBC) o025_sum_types_basic.ml -o 025_sum_types_basic

026: o026_sum_types_exceptions.ml
	$(OBC) o026_sum_types_exceptions.ml -o 026_sum_types_exceptions

027: o027_sum_types_recursive.ml
	$(OBC) o027_sum_types_recursive.ml -o 027_sum_types_recursive

028: o028_polymorphic_types.ml
	$(OBC) o028_polymorphic_types.ml -o 028_polymorphic_types

030: o030_references.ml
	$(OBC) o030_references.ml -o 030_references

031: o031_redefine_lists.ml
	$(OBC) o031_redefine_lists.ml -o 031_redefine_lists

032:
	make -C 032_number

033:
	make -C 033_nlist_record

034:
	make -C 034_nlist

035:
	make -C 035_bintree

036:
	make -C 036_advanced_io_vfs

